import keyboard as JASON
import math as SHAUN
import random as SHAAAAUUUUUNNNNNNNN
import simpleaudio as JAAAAASSSOOOOOOONNNNN

while True:
    if JASON.is_pressed('x'):
        SHAAUUUUNNNN_JAAASSSOOOOON = ["JAAAASON", "JAAAASSSOOOOON", "JASON", "SHAUN", "SHAAAAAAAAAAUUUUUUUUUUUUUUUUUNNNNNNNNNNNN", "SHAAAAUUUUNNNNN"]
        SHAAAAUUUUUNNNNNNNN.shuffle(SHAAUUUUNNNN_JAAASSSOOOOON)
        JAAAAASSSOOOOOOONNNNN.WaveObject.from_wave_file(f"./SHAAAAUUUNNN_JAAAASSOOOON/{SHAAUUUUNNNN_JAAASSSOOOOON[ SHAUN.floor((SHAAAAUUUUUNNNNNNNN.random() *  2))]}.wav").play().wait_done()
